### ISSUE TITLE
Content error: Link from Main -> Enforcement broken

### ISSUE THREAD

**Issue by twinklebob** [cornwallgeeks/cornwallgeeks.github.io#10]
From the initial page (is homepage still a term people use these days? it feels so 90s) click on Enforcement policy and you get to https://cornwallgeeks.github.io/encforcement with a 404

**Comment by CookieCookson** [comment]
PR created here: https://github.com/cornwallgeeks/cornwallgeeks.github.io/pull/13

**Comment by danreeves** [comment]
Fixed by #13
