### ISSUE TITLE
Content: Enforcement page relates to different group

### ISSUE THREAD

**Issue by twinklebob** [cornwallgeeks/cornwallgeeks.github.io#11]
The enforcement page at https://cornwallgeeks.github.io/enforcement/ refers to the WeAllJS community, e.g.:

> It is a living document, informed by new problems, new conflicts, and always strives to help make the WeAllJS community successful while including the voices of those who are too often not heard.

**Comment by CookieCookson** [comment]
Created a PR fix here: https://github.com/cornwallgeeks/cornwallgeeks.github.io/pull/12

**Comment by danreeves** [comment]
Fixed by #12
