### ISSUE TITLE
Other meetups

### ISSUE THREAD

**Issue by danreeves** [cornwallgeeks/cornwallgeeks.github.io#14]
✨ Cool Internet Webring ✨

`/friends` or `/other-meetups` for example.

Link to:

 - [ ] Cornwall Digital meetup group
 - [ ] Kernow DAT
 - [ ] Software Cornwall
 - [ ] _The_ Digital Plymouth
 - [ ] Plymouth JS
 - [ ] Who else?

**Comment by tonyedwardspz** [comment]
What kind of thing are we looking for for this page? I was thinking we could match the layout of the organisers page, with one block for each community?

Possible additions:

- [ ] Plymouth Game Devs
- [ ] MESH (parent of PlymouthJS & Plymouth.NET but does much more)
- [ ] Tech Exeter (bit of a stretch??)

**Comment by danreeves** [comment]
Yeah that sounds good, the design can support logos too.

Those additions sound good, except Exeter. Plymouth barely makes the cut. 😁

**Comment by tonyedwardspz** [comment]
Awesome. Expect a PR in the next few days. Handily, I have already gathered the logos for something else.

As I see it, Plymouth should be a part of Cornwall anyway..... Devon has Exeter :)

**Comment by danreeves** [comment]
Awesome ✌️
